### ISSUE TITLE
Как вы использовали форму границы в стиле Windows 10?

### ISSUE THREAD

**Issue by servusdei2018** [nuc134r/ExpertSystem#5]
Как вы использовали форму границы в стиле Windows 10? Я хочу реализовать нечто подобное в моем приложении.

Это отличное приложение! Продолжайте хорошую работу.

**Comment by nuc134r** [comment]
Спасибо. Это родное приложение для Windows, написанное на C# с WPF. Эти границы предоставляются системой.

Thank you. It's a native Windows app written in C# with WPF. Those borders are provided by the system.
